In [2]:
!pip install tensorflow

In [4]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [6]:
with open ("C:\\Users\\rakiv\\Downloads\\Modi.txt",'r',encoding='utf-8')as myfile:
  mytext=myfile.read()

In [8]:
mytext

'Following a lavish state visit by Indian Prime Minister Narendra Modi to Washington, US President Joe Biden has called his country\'s partnership with India among the "most consequential in the world". The BBC\'s Vikas Pandey and Soutik Biswas explore the factors that contribute to the visit\'s potential in strengthening the ties between the two nations.\n\nThe US\'s relationship with India - the world\'s most populous country - is "stronger, closer and more dynamic than any time in history", Mr Biden said at the completion of a pomp-filled state visit by Mr Modi to the White House. The remark may not be an exaggeration. "This summit suggests that the relationship has been transformed. It underscores just how broad and deep it has become in a relatively short time," says Michael Kugelman of The Wilson Center, an American think-tank.\n\nA key reason is that Washington is keen to draw India closer so that it can act as a counterbalance to China\'s growing influence in the Indo-Pacific. 

In [10]:
mytokenizer=Tokenizer()
mytokenizer.fit_on_texts([mytext])
total_words=len(mytokenizer.word_index)+1

In [12]:
mytokenizer.word_index

{'the': 1,
 'to': 2,
 'a': 3,
 'in': 4,
 'and': 5,
 'india': 6,
 'of': 7,
 'mr': 8,
 'us': 9,
 'is': 10,
 'modi': 11,
 'has': 12,
 'that': 13,
 'as': 14,
 'with': 15,
 'not': 16,
 "india's": 17,
 'for': 18,
 'but': 19,
 'biden': 20,
 'an': 21,
 'it': 22,
 'says': 23,
 'will': 24,
 'are': 25,
 'on': 26,
 'washington': 27,
 'this': 28,
 'have': 29,
 'trade': 30,
 'visit': 31,
 'by': 32,
 'indian': 33,
 'prime': 34,
 'minister': 35,
 'relationship': 36,
 'been': 37,
 'about': 38,
 'strategic': 39,
 'president': 40,
 'more': 41,
 'up': 42,
 'also': 43,
 'make': 44,
 'sirohi': 45,
 'china': 46,
 'state': 47,
 'his': 48,
 'ties': 49,
 'two': 50,
 'at': 51,
 'be': 52,
 'during': 53,
 'lot': 54,
 'ms': 55,
 'technology': 56,
 'semiconductor': 57,
 'now': 58,
 'was': 59,
 'global': 60,
 'one': 61,
 'he': 62,
 'without': 63,
 'air': 64,
 'force': 65,
 'they': 66,
 'world': 67,
 'potential': 68,
 'how': 69,
 'become': 70,
 'kugelman': 71,
 'years': 72,
 'there': 73,
 "modi's": 74,
 'jet': 75,
 'f

In [18]:
my_input_sequences=[]
for line in mytext.split('\n'):
    token_list=mytokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        my_n_gram_sequence=token_list[:i+1]
        my_input_sequences.append(my_n_gram_sequence)
        

In [26]:
max_sequence_len=max([len(seq) for seq in my_input_sequences])
input_sequences=np.array(pad_sequences(my_input_sequences,maxlen=max_sequence_len,padding='pre'))


In [28]:
input_sequences[1]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [30]:
x=input_sequences[:,:-1]
y=input_sequences[:,-1]


In [32]:
x[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [34]:
y

array([  3, 169,  47, ...,  23,  55,  45])

In [36]:
y=np.array(tf.keras.utils.to_categorical(y,num_classes=total_words))

In [38]:
y[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [44]:
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(LSTM(150))
model.add(Dense(total_words,activation='softmax'))
print(model.summary())

C:\Users\rakiv\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x,y,epochs=100,verbose=1)

Epoch 1/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 31s 648ms/step - accuracy: 0.0320 - loss: 6.2895
Epoch 2/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 37s 566ms/step - accuracy: 0.0504 - loss: 5.7669
Epoch 3/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 26s 627ms/step - accuracy: 0.0541 - loss: 5.7203
Epoch 4/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 38s 566ms/step - accuracy: 0.0597 - loss: 5.7060
Epoch 5/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 26s 626ms/step - accuracy: 0.0514 - loss: 5.5990
Epoch 6/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 39s 578ms/step - accuracy: 0.0624 - loss: 5.4439
Epoch 7/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 27s 640ms/step - accuracy: 0.0544 - loss: 5.4036
Epoch 8/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 38s 581ms/step - accuracy: 0.0780 - loss: 5.1925
Epoch 9/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 42s 599ms/step - accuracy: 0.0932 - loss: 5.0271
Epoch 10/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 24s 574ms/step - accuracy: 0.1165 - loss: 4.7537
Epoch 11/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 42s 594ms/step - accuracy: 0.1204 - loss: 4.6125
Epoch 12/100
42/42 ━━━━━━━━━━━

In [ ]:
input_text="Joe biden"
predict_next_words=6 
for _ in range(predict_next_words):
    token_list=mytokenizer.texts_to_sequences([input_text])[0]
    print(token_list)
    token_list=pad_sequences([token_list],maxlen=max_sequence_len-1,padding='pre')
    predicted=np.argmax(model.predict(token_list),axis=-1)
    output_word=""
    
    for word,index in mytokenizer.word_index.items():
        if index== predicted:
            output_word=word
            break

    input_text+="" + output_word
print(input_text)