### Introduction

In [52]:
## pytorch framework- Tensor datatypes
#### >> Tensor  are similar to Numpy arrays ,tensors can run on "GPU's"
##>>> Where as numpy arraya can't run an "GPU'S"

## Initailization tensor


In [53]:
# Initailization a Tensor
import numpy as np
data=[[1,2],[3,4]]
# converting this numpy array
np_array=np.array(data)
print(np_array.shape)
print(np_array)
print(type(np_array))

(2, 2)
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [54]:
import torch
torch_tensor=torch.Tensor(data)
print(torch.Tensor)
print(torch_tensor)
print(type(torch_tensor))

<class 'torch.Tensor'>
tensor([[1., 2.],
        [3., 4.]])
<class 'torch.Tensor'>


In [55]:
#converting numpy array to Tensor
x_tensor=torch.from_numpy(np_array)
x_tensor

tensor([[1, 2],
        [3, 4]])

In [56]:
#create a tensor of all ones similar to "x_tensor"
x_ones=torch.ones_like(x_tensor)
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [57]:
## Create a  Random tensor similar to "x_tensor"
x_random=torch.rand_like(x_tensor,dtype=torch.float) #np.float
print(x_random)


tensor([[0.6445, 0.1835],
        [0.9596, 0.1844]])


In [58]:
# Generate Tensor Shape AND create nampy array
shape=(2,3) ## 2x3x1
rand_tensor=torch.rand(shape)  ##np.random.rand
ones_tensor=torch.ones(shape)  ## np.ones
zeros_tensor=torch.zeros(shape)  ## np.zeros

In [59]:
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)
print(rand_tensor.shape)

tensor([[0.8066, 0.9117, 0.1922],
        [0.1441, 0.1263, 0.9940]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


In [60]:
## Check the Tensor Random
tensor=torch.rand(3,4)
tensor.shape
tensor.dtype
tensor.device




device(type='cpu')

In [61]:
## check the device GPU or CPU

if torch.cuda.is_available():
  tensor=tensor.to("cuda")

else:
  pass

In [62]:
tensor.device

device(type='cuda', index=0)

In [63]:
## Check the first row of tensor
tensor=torch.ones(4,4)
tensor[0]

tensor([1., 1., 1., 1.])

In [64]:
## check the first column of the tensor
tensor[:,0]


tensor([1., 1., 1., 1.])

In [65]:
## check last column of the tensor
tensor[:,-1]

tensor([1., 1., 1., 1.])

In [66]:
## Concating the Tensor
torch.cat([tensor,tensor,tensor],dim=1) # dim is Dimansional
## in pytorch does not use axis=1 only use "dim=1"

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [67]:
## arithemetic operations
t1=torch.rand(2,2)
t2=torch.rand(2,2)
#> Matrics Multiplication in numpy and pytorch
y1=t1@t2.T # (or)
y2=t1.matmul(t2.T)

In [68]:
y1

tensor([[0.2180, 0.3573],
        [0.1751, 0.3292]])

In [69]:
y2

tensor([[0.2180, 0.3573],
        [0.1751, 0.3292]])

In [70]:
# Multipli two elements [2x2 ] and [2x2]
z1=t1*t2
z1

tensor([[0.0503, 0.1676],
        [0.0043, 0.3249]])

In [71]:
z2=t1.matmul(t2) #matmul does matrix multiplication : mul does elementwise multiplication
z2 # mutmul means "matrix multiplication"

tensor([[0.1463, 0.3835],
        [0.1029, 0.3324]])

In [72]:
# Aggregation
agg=t1.sum()
agg

tensor(1.2150)

In [73]:
agg.item() ## its only give the value

1.2149665355682373

In [74]:
#Create tensor
t1=torch.ones(4,4)
t1[:,1]=0
#it's assiging the second column is "zero"
t1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [78]:
t1=torch.rand(5,5)
t1[:,1]=3
t1

tensor([[0.9684, 3.0000, 0.9736, 0.0796, 0.5031],
        [0.4285, 3.0000, 0.4333, 0.3208, 0.8929],
        [0.2635, 3.0000, 0.6278, 0.2248, 0.5225],
        [0.4180, 3.0000, 0.4400, 0.2520, 0.9605],
        [0.5750, 3.0000, 0.2214, 0.3265, 0.7473]])

In [76]:
## Adding the number
t1.add_(5)
#adding any paticular elament wecan use this "add()"


tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [81]:
# Create Numpy array
x=np.array([[1,2],[3,4]])
 # how to convert to tensor
tensor=torch.from_numpy(x)
#convert into tensor
y=tensor.numpy()
#convert into numpy array


In [82]:
type(x)


numpy.ndarray

In [83]:
type(tensor)


torch.Tensor

In [84]:
type(y)

numpy.ndarray